version: "3.9"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: my-mongodb
    restart: always
    networks:
      - app-network
    command: mongod --bind_ip 0.0.0.0  # Add this line to bind to all available network interfaces

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-node-app
    ports:
      - "5500:5500"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb+srv://aishwarya:aishwaryapass@cluster0.fah4o06.mongodb.net/?retryWrites=true&w=majority  # Use the host's IP address
    networks:
      - app-network

networks:
  app-network:
    driver: bridge